name: DevManagement

options:
  bundleIdPrefix: com.zivtal
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.10"
    MARKETING_VERSION: "1.5.3"
    CURRENT_PROJECT_VERSION: "54"
    DEVELOPMENT_TEAM: 52HV33827A
    CODE_SIGN_STYLE: Automatic

targets:
  DevManagement:
    type: application
    platform: macOS
    sources:
      - Sources
      - path: Resources
        buildPhase: resources
    dependencies:
      - sdk: IOKit.framework
      - sdk: Security.framework
      - sdk: UserNotifications.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zivtal.DevManagement
        PRODUCT_NAME: Development Management
        PRODUCT_MODULE_NAME: DevManagement
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: Development Management
        INFOPLIST_KEY_CFBundleShortVersionString: $(MARKETING_VERSION)
        INFOPLIST_KEY_CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.developer-tools
        INFOPLIST_KEY_LSUIElement: true
        ENABLE_APP_SANDBOX: false
        ENABLE_HARDENED_RUNTIME: true
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon


  DevManagementTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests
    dependencies:
      - target: DevManagement
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zivtal.DevManagementTests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Development Management.app/Contents/MacOS/Development Management"

schemes:
  DevManagement:
    build:
      targets:
        DevManagement: all
        DevManagementTests:
          - test
    test:
      targets:
        - DevManagementTests
